// Code generated by protoc-gen-go. DO NOT EDIT.
// source: persontData.proto

package entity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersonData struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	MobileNumber         string   `protobuf:"bytes,4,opt,name=MobileNumber,json=mobileNumber,proto3" json:"MobileNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonData) Reset()         { *m = PersonData{} }
func (m *PersonData) String() string { return proto.CompactTextString(m) }
func (*PersonData) ProtoMessage()    {}
func (*PersonData) Descriptor() ([]byte, []int) {
	return fileDescriptor_514564abcf26737d, []int{0}
}

func (m *PersonData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonData.Unmarshal(m, b)
}
func (m *PersonData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonData.Marshal(b, m, deterministic)
}
func (m *PersonData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonData.Merge(m, src)
}
func (m *PersonData) XXX_Size() int {
	return xxx_messageInfo_PersonData.Size(m)
}
func (m *PersonData) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonData.DiscardUnknown(m)
}

var xxx_messageInfo_PersonData proto.InternalMessageInfo

func (m *PersonData) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PersonData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PersonData) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*PersonData)(nil), "entity.PersonData")
}

func init() { proto.RegisterFile("persontData.proto", fileDescriptor_514564abcf26737d) }

var fileDescriptor_514564abcf26737d = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0x2b, 0x71, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b,
	0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0x54, 0xca, 0xe2, 0xe2, 0x0a, 0x00, 0x4b, 0x82, 0xe4, 0x84, 0xf8,
	0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x5d, 0x84, 0x84,
	0xb8, 0x58, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x58, 0xf2, 0x12,
	0x73, 0x53, 0x85, 0x44, 0xb8, 0x58, 0x5d, 0x73, 0x13, 0x33, 0x73, 0x24, 0x98, 0xc1, 0x82, 0xac,
	0xa9, 0x20, 0x8e, 0x90, 0x12, 0x17, 0x8f, 0x6f, 0x7e, 0x52, 0x66, 0x4e, 0xaa, 0x5f, 0x69, 0x6e,
	0x52, 0x6a, 0x91, 0x04, 0x0b, 0x58, 0x92, 0x27, 0x17, 0x49, 0x2c, 0x89, 0x0d, 0x6c, 0xb5, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x03, 0x8e, 0x19, 0x9e, 0x8f, 0x00, 0x00, 0x00,
}
